### PR TITLE
Add TFT_eSPI_ESP32_C6.c and TFT_eSPI_ESP32_C6.h

### PR DESCRIPTION
**Pull request by Cincinnatu**
I added TFT_eSPI_ESP32_C6.c and TFT_eSPI_ESP32_C6.h to fix the ESP32C6 compilation error. 
When using the TFT_eSPI library on Arduino, I found that using TFT_eSPI_ESP32 did not compile correctly. After several attempts and modifications, I finally chose to add the files TFT_eSPI_ESP32_C6.c and TFT_eSPI_ESP32_C6.h to resolve the compilation issues

### CODE REVIEW

**Comment by OscarTofa** [comment]
I am trying the new files you made. at the compilation level there are no errors but when I go to load the esp32c6 program it crashes and restarts. 
11:50:40.866 -> [   817][V][esp32-hal-periman.c:235] perimanSetBusDeinit(): Deinit function for type GPIO (1) successfully set to 0x4200d956
11:50:40.866 -> [   817][V][esp32-hal-periman.c:160] perimanSetPinBus(): Pin 14 successfully set to type GPIO (1) with bus 0xf
11:50:40.866 -> [   818][V][esp32-hal-periman.c:160] perimanSetPinBus(): Pin 14 successfully set to type SPI_MASTER_MOSI (36) wiGuru Meditation Error: Core  0 panic'ed (Store access fault). Exception was unhandled.
11:50:41.218 -> 
11:50:41.218 -> Core  0 register dump:

File: Processors/TFT_eSPI_ESP32_C6.c [hunk 1]
```diff
@@ -0,0 +1,862 @@
...
+uint8_t TFT_eSPI::readByte(void)
+{
+  uint8_t b = 0xAA;
+
+#if defined (TFT_PARALLEL_8_BIT)
+  RD_L;
+  uint32_t reg;           // Read all GPIO pins 0-31
+  reg = gpio_input_get(); // Read three times to allow for bus access time
+  reg = gpio_input_get();
+  reg = gpio_input_get(); // Data should be stable now
```
Comment (crmbz0r) [inline Processors/TFT_eSPI_ESP32_C6.c:109]:
```suggestion
      reg |= (gpio_get_level((gpio_num_t)i) << (i - TFT_D0));
  }
```

File: Processors/TFT_eSPI_ESP32_C6.h [hunk 2]
```diff
@@ -0,0 +1,598 @@
...
+// Include processor specific header
+#include "soc/spi_reg.h"
+#include "driver/spi_master.h"
+#include "hal/gpio_ll.h"
+
+#if !defined(CONFIG_IDF_TARGET_ESP32C3) && !defined(CONFIG_IDF_TARGET_ESP32S2) && !defined(CONFIG_IDF_TARGET_ESP32)
+  #define CONFIG_IDF_TARGET_ESP32
+#endif
+
+#ifndef VSPI
```
Comment (crmbz0r) [inline Processors/TFT_eSPI_ESP32_C6.h:26]:
```suggestion
#ifndef FSPI
```

Comment (crmbz0r) [reply Processors/TFT_eSPI_ESP32_C6.h:26]: And of course I changed all of them to FSPI in the header too. :D

File: Processors/TFT_eSPI_ESP32_C6.h [hunk 3]
```diff
@@ -0,0 +1,598 @@
...
+  #define VSPI FSPI
```
Comment (crmbz0r) [inline Processors/TFT_eSPI_ESP32_C6.h:27]:
```suggestion
  #define FSPI FSPI
```

File: Processors/TFT_eSPI_ESP32_C6.h [hunk 4]
```diff
@@ -0,0 +1,598 @@
...
+  #define T_CS_L digitalWrite(TOUCH_CS, LOW)
+  #define T_CS_H digitalWrite(TOUCH_CS, HIGH)
+#endif
+
+////////////////////////////////////////////////////////////////////////////////////////
+// Make sure SPI default pins are assigned if not specified by user or set to -1
+////////////////////////////////////////////////////////////////////////////////////////
+#if !defined (TFT_PARALLEL_8_BIT)
+
+  #ifdef USE_HSPI_PORT
```
Comment (crmbz0r) [inline Processors/TFT_eSPI_ESP32_C6.h:272]:
```suggestion
  #ifdef USE_FSPI_PORT
```

**Review by crmbz0r — CHANGES_REQUESTED** [review]
I have marked the changes that I made for myself which seem to have made it work. I've compiled probably 50 times successfully already with these files and the small changes made. 
Also, here is a setup that finally worked with the pins and no errors or faulty connections to a ILI9488 TFT LCD shield via parallel.
When running the test on the pins, I had to put the GPIO printed number into the user setup file (where I also connected the cables to) and the actual pin number into the test code I ran to check the connections (you will see what I mean in the comments behind the pins).
Not sure if that is "normal", I always thought that the written GPIO names are used but apparently not.. well whatever, I am not that long into ESP32 coding stuff, but at least I can compile my stuff with the ILI9488 now :)



```
#include <driver/gpio.h> 
#define USER_SETUP_ID 70

#define ILI9488_DRIVER    
#define TFT_PARALLEL_8_BIT

#define TFT_CS   23     //   testPin(21, "TFT_CS");  // GPIO23
#define TFT_DC   19     //   testPin(17, "TFT_DC");  // GPIO19
#define TFT_RST   1     //   testPin(9, "TFT_RST");  // GPIO1
#define TFT_WR   11     //   testPin(12, "TFT_WR");  // GPIO11
#define TFT_RD    0     //   testPin(8, "TFT_RD");  // GPIO0

#define TFT_D0    4     //   testPin(4, "TFT_D0");  // GPIO4
#define TFT_D1    5     //   testPin(5, "TFT_D1");  // GPIO5
#define TFT_D2   12     //   testPin(13, "TFT_D2");  // GPIO12
#define TFT_D3   13     //   testPin(14, "TFT_D3");  // GPIO23
#define TFT_D4   18     //   testPin(16, "TFT_D4");  // GPIO18
#define TFT_D5    6     //   testPin(6, "TFT_D5");  // GPIO6
#define TFT_D6    7     //   testPin(7, "TFT_D6");   // GPIO7
#define TFT_D7   22     //   testPin(20, "TFT_D7");   // GPIO22

#define LOAD_GLCD
#define LOAD_FONT2
#define LOAD_FONT4
#define LOAD_FONT6
#define LOAD_FONT7
#define LOAD_FONT8  
#define LOAD_GFXFF  

#define SMOOTH_FONT

// #define SPI_FREQUENCY   1000000
// #define SPI_FREQUENCY   5000000
// #define SPI_FREQUENCY  10000000
//#define SPI_FREQUENCY  20000000
#define SPI_FREQUENCY  27000000

#define SPI_READ_FREQUENCY  20000000
```

**Comment by AlanChatflix** [comment]
With the official Espressif ESP32-C6-DevKitC-1-N8 Development Board ([Amazon](https://www.amazon.com/dp/B0BRMSDR4R?ref=ppx_yo2ov_dt_b_product_details&th=1)) connected to a 2.8 TFT Display 240x320 (touch display) which works perfectly on MEGA Arduinos with ILI9341 DRIVER.

**I tried your update on my code by:**
--
Copying: TFT_eSPI_ESP32_C6.c
Copying: TFT_eSPI_ESP32_C6.h
Updating: TFT_eSPI.cpp
Updating: TFT_eSPI.h
--
But it still doesn't work at all. 
First of all, this ESP32 has no VSPI, it's FSPI:

image

I get it to compile when I do:

`#define USE_FSPI_PORT`

But then it keeps crashing and rebooting with this error:

**Guru Meditation Error: Core  0 panic'ed (Store access fault). Exception was unhandled.**

I also tried with ILI9341_2_DRIVER, but the same happens.

**Can you guys check this and see if there's any quick fix?**

**Comment by AlanChatflix** [comment]
> With the official Espressif ESP32-C6-DevKitC-1-N8 Development Board ([Amazon](https://www.amazon.com/dp/B0BRMSDR4R?ref=ppx_yo2ov_dt_b_product_details&th=1)) connected to a 2.8 TFT Display 240x320 (touch display) which works perfectly on MEGA Arduinos with ILI9341 DRIVER.
> 
> ## **I tried your update on my code by:**
> ## Copying: TFT_eSPI_ESP32_C6.c
> Copying: TFT_eSPI_ESP32_C6.h
> Updating: TFT_eSPI.cpp
> Updating: TFT_eSPI.h
> But it still doesn't work at all. First of all, this ESP32 has no VSPI, it's FSPI:
> 
> image
> 
> I get it to compile when I do:
> 
> `#define USE_FSPI_PORT`
> 
> But then it keeps crashing and rebooting with this error:
> 
> **Guru Meditation Error: Core 0 panic'ed (Store access fault). Exception was unhandled.**
> 
> I also tried with ILI9341_2_DRIVER, but the same happens.
> 
> **Can you guys check this and see if there's any quick fix?**

@crmbz0r

**Comment by bosco-drg** [comment]
Hello, do you have any new solutions to use the display with esp32 c6 ?

**Comment by emblink** [comment]
Hi, I am trying to use TFT_eSPI with the XIAO ESP32-C6.  I pulled PR #3399, which resolves the compilation issues for this MCU in Arduino IDE. However, I still cannot get my ST7789 240x240 display working. The wiring and pinout are correct, as it functions with other libraries. Is there anything else needed to make this work on the ESP32-C6? Any advice or insights would be greatly appreciated!

**Comment by DanielBrkr** [comment]
@emblink I got it working yesterday with a pretty similar setup (same display controller), I think you need to enable `#define TFT_SDA_READ` and `#define TFT_BACKLIGHT_ON HIGH  // Level to turn ON back-light (HIGH or LOW)` in the User_Setup.h file.
Let me know if that works, happy to help if not

**Comment by emblink** [comment]
Hi @DanielBrkr,
Thank you so much! `#define TFT_SDA_READ` resolved the issue. 
It’s a bit tricky, as it's not directly mentioned in `#include <User_Setups/Setup24_ST7789.h>`. I didn’t wire the MISO line to the display, and since my setup worked with Adafruit_ST7789.h, I didn’t expect a "read" operation to be needed here. I also commented out `User_Setup.h` and missed the `TFT_SDA_READ` reference there—my mistake!

Thanks again for your help!

**Comment by Cincinnatu** [comment]
This is the final version modified based on the reference.：https://github.com/Cincinnatu/TFT_eSPI

**Comment by Nushio** [comment]
FYI, I bought a Waveshare ESPC6-LCD-1.47 device and this PR made it compile properly. Thanks!

**Comment by MagnusThome** [comment]
> This is the final version modified based on the reference.：https://github.com/Cincinnatu/TFT_eSPI


Works great with Waveshare ESP32-C6 with built in 1.47" screen. Thank you!

Really really hope this gets included into bodmers

**Review by MagnusThome — COMMENTED** [review]
Works well with Waveshare ESP32-C6 with built ion 1.47"

Can't see anything odd when glancing through the code.

**Comment by theepicflyer** [comment]
Hey @MagnusThome and @Nushio, can I check what setup settings did you use with the Waveshare ESP32-C6-LCD-1.47? This is what I created using the schematic from the Waveshare website but there does not seem to be any display, only backlight.

```
#define USER_SETUP_ID 999

#define ST7789_DRIVER      // Full configuration option, define additional parameters below for this display

#define TFT_SDA_READ      // This option is for ESP32 ONLY, tested with ST7789 and GC9A01 display only

// #define TFT_RGB_ORDER TFT_BGR  // Colour order Blue-Green-Red

#define TFT_WIDTH  172
#define TFT_HEIGHT 320

#define TFT_BL   22            // LED back-light control pin
#define TFT_BACKLIGHT_ON HIGH  // Level to turn ON back-light (HIGH or LOW)

#define TFT_MOSI 6
#define TFT_SCLK 7
#define TFT_CS   14   // Chip select control pin
#define TFT_DC   15  // Data Command control pin
#define TFT_RST  21  // Reset pin (could connect to RST pin)

#define LOAD_GLCD   // Font 1. Original Adafruit 8 pixel font needs ~1820 bytes in FLASH
#define LOAD_FONT2  // Font 2. Small 16 pixel high font, needs ~3534 bytes in FLASH, 96 characters
#define LOAD_FONT4  // Font 4. Medium 26 pixel high font, needs ~5848 bytes in FLASH, 96 characters
#define LOAD_FONT6  // Font 6. Large 48 pixel font, needs ~2666 bytes in FLASH, only characters 1234567890:-.apm
#define LOAD_FONT7  // Font 7. 7 segment 48 pixel font, needs ~2438 bytes in FLASH, only characters 1234567890:-.
#define LOAD_FONT8  // Font 8. Large 75 pixel font needs ~3256 bytes in FLASH, only characters 1234567890:-.
#define LOAD_GFXFF  // FreeFonts. Include access to the 48 Adafruit_GFX free fonts FF1 to FF48 and custom fonts
#define SMOOTH_FONT

#define SPI_FREQUENCY  27000000
```

**Comment by MagnusThome** [comment]
You are missing the MISO pin

```
// Support for 1.47" 320x172 Round Rectangle Color IPS TFT Display
#define USER_SETUP_ID 71

#define ST7789_DRIVER  // Full configuration option, define additional parameters below for this display

#define TFT_RGB_ORDER TFT_BGR  // Colour order Blue-Green-Red

#define TFT_WIDTH 172  // ST7789 172 x 320
#define TFT_HEIGHT 320  // ST7789 240 x 320

#define TFT_BL           22    // LED back-light control pin
#define TFT_BACKLIGHT_ON HIGH  // Level to turn ON back-light (HIGH or LOW)

#define TFT_MISO 5
#define TFT_MOSI 6
#define TFT_SCLK 7
#define TFT_CS   14   // Chip select control pin
#define TFT_DC   15  // Data Command control pin
#define TFT_RST  21  // Reset pin (could connect to RST pin)

#define LOAD_GLCD   // Font 1. Original Adafruit 8 pixel font needs ~1820 bytes in FLASH
#define LOAD_FONT2  // Font 2. Small 16 pixel high font, needs ~3534 bytes in FLASH, 96 characters
#define LOAD_FONT4  // Font 4. Medium 26 pixel high font, needs ~5848 bytes in FLASH, 96 characters
#define LOAD_FONT6  // Font 6. Large 48 pixel font, needs ~2666 bytes in FLASH, only characters 1234567890:-.apm
#define LOAD_FONT7  // Font 7. 7 segment 48 pixel font, needs ~2438 bytes in FLASH, only characters 1234567890:-.
#define LOAD_FONT8  // Font 8. Large 75 pixel font needs ~3256 bytes in FLASH, only characters 1234567890:-.
//#define LOAD_FONT8N // Font 8. Alternative to Font 8 above, slightly narrower, so 3 digits fit a 160 pixel TFT
#define LOAD_GFXFF  // FreeFonts. Include access to the 48 Adafruit_GFX free fonts FF1 to FF48 and custom fonts

#define SMOOTH_FONT

#define SPI_FREQUENCY 80000000
```

**Comment by Nushio** [comment]
```

#define USER_SETUP_INFO "User_Setup"

#define ST7789_DRIVER // Full configuration option, define additional parameters below for this display

#define TFT_RGB_ORDER TFT_BGR

#define TFT_WIDTH 172  // ST7789 172 x 320
#define TFT_HEIGHT 320 // ST7789 240 x 320

#define TFT_BL 22             // LED back-light control pin
#define TFT_BACKLIGHT_ON HIGH // Level to turn ON back-light (HIGH or LOW)

#define TFT_MISO 5
#define TFT_MOSI 6
#define TFT_SCLK 7
#define TFT_CS 14  // Chip select control pin
#define TFT_DC 15  // Data Command control pin
#define TFT_RST 21 // Reset pin (could connect to RST pin)

#define LOAD_GLCD  // Font 1. Original Adafruit 8 pixel font needs ~1820 bytes in FLASH
#define LOAD_FONT2 // Font 2. Small 16 pixel high font, needs ~3534 bytes in FLASH, 96 characters
#define LOAD_FONT4 // Font 4. Medium 26 pixel high font, needs ~5848 bytes in FLASH, 96 characters

#define SPI_FREQUENCY 80000000

#define SPI_READ_FREQUENCY 20000000

#define SPI_TOUCH_FREQUENCY 2500000
```




But, in my main setup code, I added:

```
#define TFT_BACKLIGHT 22
#define Frequency 1000 
#define Resolution 10  
void setup()
{
  ledcAttach(TFT_BACKLIGHT, Frequency, Resolution);
  ledcWrite(TFT_BACKLIGHT, 90); // Lowers screen brightness to 90%, 100% runs too hot IMO
}
```

**Comment by theepicflyer** [comment]
Thank you both.

**Comment by ShocKwav3** [comment]
Thanks a lot for this PR! I tested on a waveshare ESP32-C6-LCD-1.47 and worked fine.

**Comment by poucotm** [comment]
Thanks for all you guys.
I'm a noob. I want it to work with a Waveshare ESP32-C6-LCD-1.47 (172x320) board. someboy can help me out ?
Do I have to clone Bodmer/TFT_eSPI or Cincinnatu's ?
Then, Do I have to replace User_Setup.h with @Nushio 's 1st comment at all ?
Then, Do I have to put the code in which @Nushio 's 2nd comment ?
I appreciate in advance.

**Comment by JayWayAr** [comment]
> Thanks for all you guys. I'm a noob. I want it to work with a Waveshare ESP32-C6-LCD-1.47 (172x320) board. someboy can help me out ? Do I have to clone Bodmer/TFT_eSPI or Cincinnatu's ? Then, Do I have to replace User_Setup.h with @Nushio 's 1st comment at all ? Then, Do I have to put the code in which @Nushio 's 2nd comment ? I appreciate in advance.

Fellow Noob here too. I used Cincinnatu's fork. Just  copied everything into the libraries folder. Then I have Magnus's User_Setup.h, except the first #define, for which I use #define USER_SETUP_INFO "User_Setup".

**Comment by poucotm** [comment]
@JayWayAr THANKS A LOT! It works in Arduino IDE.
Actually, my goal is to use TFT_eSPI with ESP-IDF directly. Anyone knows about ?

**Comment by teastainGit** [comment]
Thank you, all of you!
I got my WaveShare C6 LCD 1.47 working with my HotHead test demo!
Cheers, Terry

**Comment by syesjohnny** [comment]
Can someone help?
It only response me Guru Meditation Error: Core 0 panic'ed (Store access fault). Exception was unhandled.

**Comment by merc07** [comment]
Hey, Thanks, I managed to get my esp32_c6 1.9 Touch display 7789 to work with your TFT_eSPI mods but for the life of me can't get the touch to work. 
Do you have any ideas ?

**Comment by slrxmartin** [comment]
@Nushio huge thanks for the setup and all that stuff!

**Comment by slrxmartin** [comment]
@merc07 it does not have touch if I remember correctly

**Comment by teastainGit** [comment]
> Hey, Thanks, I managed to get my esp32_c6 1.9 Touch display 7789 to work with your TFT_eSPI mods but for the life of me can't get the touch to work. Do you have any ideas ?

Is this the Waveshare unit?
https://www.waveshare.com/wiki/ESP32-C6-LCD-1.9
it uses the I2C_QMI8658 touch overlay

**Comment by merc07** [comment]
Yes the Waveshare - You are correct, it is IC2 but the CST816
Figured that yesterday, hence the TFT eSPI doesn't work..

CST816S touch(18, 8, 21, 22);  // sda, scl, rst, irq
Still it seems none of the CST816 libraries work :(

**Comment by arpy8** [comment]
> > Thanks for all you guys. I'm a noob. I want it to work with a Waveshare ESP32-C6-LCD-1.47 (172x320) board. someboy can help me out ? Do I have to clone Bodmer/TFT_eSPI or Cincinnatu's ? Then, Do I have to replace User_Setup.h with @Nushio 's 1st comment at all ? Then, Do I have to put the code in which @Nushio 's 2nd comment ? I appreciate in advance.
> 
> Fellow Noob here too. I used Cincinnatu's fork. Just copied everything into the libraries folder. Then I have Magnus's User_Setup.h, except the first #define, for which I use #define USER_SETUP_INFO "User_Setup".

HOLY SHIT Thank you so much guys, I've been trying to figure out this for like 6 hours, y'all saved me. THANK YOU @Cincinnatu

**Comment by dom96** [comment]
This seems like a pretty simple patch, any chance it could be merged in?

**Comment by billlowe** [comment]
Can anyone explain how to use this? Just for a change of pace - how is this done? Where are the files? TFT_eSPI_ESP32_C6.c and h?

If I finally make them can I upload them here so people can download them?

**Review by elagin — APPROVED** [review]
I tested it with the GC9A01 – the compilation error no longer occurs. The display shows what it should.

**Comment by Git-Jay13** [comment]
> Hey, Thanks, I managed to get my esp32_c6 1.9 Touch display 7789 to work with your TFT_eSPI mods but for the life of me can't get the touch to work. 
> 
> Do you have any ideas ?
Would you please upload your files so that I can use them? I've been trying to get my waveshare ESP32 c6 1.9 inch touch display working forever!!

**Comment by Git-Jay13** [comment]
> Can anyone explain how to use this? Just for a change of pace - how is this done? Where are the files? TFT_eSPI_ESP32_C6.c and h?
> 
> 
> 
> If I finally make them can I upload them here so people can download them? 

Yes please upload them!

**Comment by Git-Jay13** [comment]
> Hey, Thanks, I managed to get my esp32_c6 1.9 Touch display 7789 to work with your TFT_eSPI mods but for the life of me can't get the touch to work. 
> 
> Do you have any ideas ?

Hey can you PLEASE upload your firmware code for the 1.9 inch c6 board. I have the same one and have not gotten it to work!!! I've been looking and trying this for so long now!! I am so close to finally being able to use my board!

**Comment by Git-Jay13** [comment]
Can one of you please upload the finished working firmware file for the waveshare C6!?! I have the 1.9 inch capacitive touch display, I've had it for almost a year now and haven't been able to get it to work so I just put it aside for a while. But this is the first time I've seen a good amount of people that got it to work with the same board! Some it’s a different size display but I can edit that or someone hopefully will upload the 1.9 inch!!!

**Comment by arpy8** [comment]
Did you get it? @Git-Jay13
